### PR TITLE
Adds filter features

### PR DESCRIPTION
**Pull request by kranrao**

### CODE REVIEW

**Comment by kranrao** [comment]
We should ultimately get rid of action window at bottom of map view.  Can now be in filter.

**Comment by cannoneyed** [comment]
OK, sounds good

**Comment by cannoneyed** [comment]
Also, will you resubmit this pull request to make the history cleaner? I just merged something like 20 seconds before you submitted it :P

**Comment by kranrao** [comment]
haha for sure

**Pull request closed without merging**
